// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutoring.Infrastructure.Persistence;

#nullable disable

namespace Tutoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TutoringDbContext))]
    [Migration("20260808150615_Id_assign_change")]
    partial class Id_assign_change
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tutoring.Domain.Billing.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TutoringAgreementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TutoringAgreementId");

                    b.HasKey("Id");

                    b.HasIndex("TutoringAgreementId")
                        .IsUnique();

                    b.ToTable("BillingAccounts", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Billing.LessonCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BillingAccountId");

                    b.Property<DateTimeOffset>("ChargedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LessonId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("LessonCharges", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BillingAccountId");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Reference");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Identity.UserAccountRole", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserAccountId");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserAccountId", "Role");

                    b.ToTable("UserAccountRoles", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.LearningMaterials.LearningMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TutorId");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("LearningMaterials", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.LearningMaterials.MaterialAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LearningMaterialId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearningMaterialId");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LessonId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TutoringAgreementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TutoringAgreementId");

                    b.HasKey("Id");

                    b.HasIndex("LearningMaterialId");

                    b.HasIndex("LessonId");

                    b.HasIndex("TutoringAgreementId");

                    b.HasIndex("LearningMaterialId", "TutoringAgreementId")
                        .IsUnique()
                        .HasFilter("[LessonId] IS NULL");

                    b.HasIndex("LearningMaterialId", "TutoringAgreementId", "LessonId")
                        .IsUnique()
                        .HasFilter("[LessonId] IS NOT NULL");

                    b.ToTable("MaterialAssignments", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CancellationReason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TutoringAgreementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TutoringAgreementId");

                    b.HasKey("Id");

                    b.HasIndex("TutoringAgreementId");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Lessons.LessonNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("CoveredTopics")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LessonId");

                    b.Property<string>("StudentProgress")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("LessonNotes", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.StudentInvitations.StudentInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TutorId");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("StudentInvitations", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.TutoringAgreements.TutoringAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PrivateNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StudentId");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TutorId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutoringAgreements", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Tutors.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Tutors", (string)null);
                });

            modelBuilder.Entity("Tutoring.Domain.Billing.BillingAccount", b =>
                {
                    b.HasOne("Tutoring.Domain.TutoringAgreements.TutoringAgreement", "Agreement")
                        .WithOne()
                        .HasForeignKey("Tutoring.Domain.Billing.BillingAccount", "TutoringAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agreement");
                });

            modelBuilder.Entity("Tutoring.Domain.Billing.LessonCharge", b =>
                {
                    b.HasOne("Tutoring.Domain.Billing.BillingAccount", null)
                        .WithMany("Charges")
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutoring.Domain.Lessons.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Tutoring.Domain.Billing.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("LessonChargeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("char(3)")
                                .HasColumnName("CurrencyCode");

                            b1.HasKey("LessonChargeId");

                            b1.ToTable("LessonCharges");

                            b1.WithOwner()
                                .HasForeignKey("LessonChargeId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Tutoring.Domain.Billing.Payment", b =>
                {
                    b.HasOne("Tutoring.Domain.Billing.BillingAccount", null)
                        .WithMany("Payments")
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tutoring.Domain.Billing.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("char(3)")
                                .HasColumnName("CurrencyCode");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Tutoring.Domain.Identity.UserAccount", b =>
                {
                    b.OwnsOne("Tutoring.Domain.Identity.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Tutoring.Domain.Identity.PersonalProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UserName");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Tutoring.Domain.Common.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_UserAccounts_Email");

                            b1.ToTable("UserAccounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Tutoring.Domain.Identity.UserAccountRole", b =>
                {
                    b.HasOne("Tutoring.Domain.Identity.UserAccount", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tutoring.Domain.LearningMaterials.LearningMaterial", b =>
                {
                    b.HasOne("Tutoring.Domain.Tutors.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Tutoring.Domain.LearningMaterials.FileDescriptor", "File", b1 =>
                        {
                            b1.Property<Guid>("LearningMaterialId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ContentType");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("FileName");

                            b1.HasKey("LearningMaterialId");

                            b1.ToTable("LearningMaterials");

                            b1.WithOwner()
                                .HasForeignKey("LearningMaterialId");

                            b1.OwnsOne("Tutoring.Domain.LearningMaterials.FileSize", "Size", b2 =>
                                {
                                    b2.Property<Guid>("FileDescriptorLearningMaterialId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<long>("Bytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("FileSizeBytes");

                                    b2.HasKey("FileDescriptorLearningMaterialId");

                                    b2.ToTable("LearningMaterials");

                                    b2.WithOwner()
                                        .HasForeignKey("FileDescriptorLearningMaterialId");
                                });

                            b1.OwnsOne("Tutoring.Domain.LearningMaterials.StorageLocation", "StorageLocation", b2 =>
                                {
                                    b2.Property<Guid>("FileDescriptorLearningMaterialId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(1024)
                                        .HasColumnType("nvarchar(1024)")
                                        .HasColumnName("StorageLocation");

                                    b2.HasKey("FileDescriptorLearningMaterialId");

                                    b2.ToTable("LearningMaterials");

                                    b2.WithOwner()
                                        .HasForeignKey("FileDescriptorLearningMaterialId");
                                });

                            b1.Navigation("Size")
                                .IsRequired();

                            b1.Navigation("StorageLocation")
                                .IsRequired();
                        });

                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Tutoring.Domain.LearningMaterials.MaterialAssignment", b =>
                {
                    b.HasOne("Tutoring.Domain.LearningMaterials.LearningMaterial", "LearningMaterial")
                        .WithMany()
                        .HasForeignKey("LearningMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tutoring.Domain.Lessons.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tutoring.Domain.TutoringAgreements.TutoringAgreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("TutoringAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agreement");

                    b.Navigation("LearningMaterial");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Tutoring.Domain.Lessons.Lesson", b =>
                {
                    b.HasOne("Tutoring.Domain.TutoringAgreements.TutoringAgreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("TutoringAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Tutoring.Domain.Lessons.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("LessonId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("EndsAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("EndsAtUtc");

                            b1.Property<DateTimeOffset>("StartsAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("StartsAtUtc");

                            b1.HasKey("LessonId");

                            b1.ToTable("Lessons");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");
                        });

                    b.Navigation("Agreement");

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("Tutoring.Domain.Lessons.LessonNote", b =>
                {
                    b.HasOne("Tutoring.Domain.Lessons.Lesson", null)
                        .WithOne("Note")
                        .HasForeignKey("Tutoring.Domain.Lessons.LessonNote", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tutoring.Domain.StudentInvitations.StudentInvitation", b =>
                {
                    b.HasOne("Tutoring.Domain.Tutors.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Tutoring.Domain.Common.EmailAddress", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("StudentInvitationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("RecipientEmail");

                            b1.HasKey("StudentInvitationId");

                            b1.ToTable("StudentInvitations");

                            b1.WithOwner()
                                .HasForeignKey("StudentInvitationId");
                        });

                    b.Navigation("Recipient")
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Tutoring.Domain.Students.Student", b =>
                {
                    b.HasOne("Tutoring.Domain.Identity.UserAccount", "Account")
                        .WithOne()
                        .HasForeignKey("Tutoring.Domain.Students.Student", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Tutoring.Domain.TutoringAgreements.TutoringAgreement", b =>
                {
                    b.HasOne("Tutoring.Domain.Students.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tutoring.Domain.Tutors.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Tutoring.Domain.TutoringAgreements.HourlyRate", "HourlyRate", b1 =>
                        {
                            b1.Property<Guid>("TutoringAgreementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("TutoringAgreementId");

                            b1.ToTable("TutoringAgreements");

                            b1.WithOwner()
                                .HasForeignKey("TutoringAgreementId");

                            b1.OwnsOne("Tutoring.Domain.Billing.Money", "PricePerHour", b2 =>
                                {
                                    b2.Property<Guid>("HourlyRateTutoringAgreementId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("HourlyRateAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("char(3)")
                                        .HasColumnName("HourlyRateCurrencyCode");

                                    b2.HasKey("HourlyRateTutoringAgreementId");

                                    b2.ToTable("TutoringAgreements");

                                    b2.WithOwner()
                                        .HasForeignKey("HourlyRateTutoringAgreementId");
                                });

                            b1.Navigation("PricePerHour")
                                .IsRequired();
                        });

                    b.OwnsOne("Tutoring.Domain.TutoringAgreements.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("TutoringAgreementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SubjectName");

                            b1.HasKey("TutoringAgreementId");

                            b1.ToTable("TutoringAgreements");

                            b1.WithOwner()
                                .HasForeignKey("TutoringAgreementId");
                        });

                    b.Navigation("HourlyRate")
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject")
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Tutoring.Domain.Tutors.Tutor", b =>
                {
                    b.HasOne("Tutoring.Domain.Identity.UserAccount", "Account")
                        .WithOne()
                        .HasForeignKey("Tutoring.Domain.Tutors.Tutor", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Tutoring.Domain.Billing.BillingAccount", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Tutoring.Domain.Identity.UserAccount", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Tutoring.Domain.Lessons.Lesson", b =>
                {
                    b.Navigation("Note");
                });
#pragma warning restore 612, 618
        }
    }
}
